name: Run dependency checks for glaes

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual run' 
  push:
    branches: 
      - main

  
jobs:
    TestGLAES:
        name: Test gdal=(${{ matrix.gdal-version }}, on ${{ matrix.os }} for glaes=${{ matrix.glaes-version }})
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: ["ubuntu-latest","ubuntu-20.04", "macos-latest","macos-13","macos-12", "macos-11","windows-latest","windows-2019"]
                # os: ["ubuntu-latest"]
                glaes-version: ["1.2.1"]
                gdal-version: ["2.4.0","2.4.1","2.4.2","2.4.3","2.4.4"]
                # gdal-version: ["2.4.1"]
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            repository: FZJ-IEK3-VSA/glaes
            path: './glaes'  
            ref: v${{ matrix.glaes-version }}
            fetch-depth: 0
        - uses: conda-incubator/setup-miniconda@v3
          with:
            miniforge-version: latest
            channels: conda-forge
            activate-environment: test_env
        - name: Run tests
          shell: pwsh
          run: |
            ls
            echo "LS Done"
            echo ${{ matrix.glaes-version }}
            echo "Glaes version is printed"
            mamba install -n test_env glaes=${{ matrix.glaes-version }} gdal=${{ matrix.gdal-version }} pytest 
            echo "Installation done"
            conda list
            echo "libaries printed"
            echo "change directory to gdal folder"
            ls
            cd glaes
            echo "change directory once more to gdal  folder"
            ls
            cd glaes
            echo "start pytest"
            conda run -n test_env python -m pytest test/
            echo "Pytest done"


