name: Run combined tests for fine
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual run' 
  push:
    branches: 
      - main

  
jobs:
    TestGeokitCondaForge:
        name: Test (${{ matrix.fine-version }}, on ${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: ["ubuntu-latest","ubuntu-20.04", "macos-latest","macos-13","macos-12", "macos-11","windows-latest","windows-2019"]
                # fine-version: ["2.3.4","2.3.3","2.3.2","2.3.1","2.3.0","2.2.3","2.2.2"]
                fine-version: ["2.3.2","2.3.1","2.3.0","2.2.3","2.2.2"]
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            repository: FZJ-IEK3-VSA/FINE
            path: './fine'  
            ref: v${{ matrix.fine-version }}
            fetch-depth: 0
        - uses: conda-incubator/setup-miniconda@v3
          with:
            miniforge-version: latest
            channels: conda-forge
            activate-environment: test_env
        - name: Run tests
          shell: pwsh
          run: |
            ls
            echo "LS Done"
            echo ${{ matrix.fine-version }}
            echo "Fine version is printed"
            mamba install -n test_env fine=${{ matrix.fine-version }} pytest=6.2.4 scikit-learn=1.1.3
            echo "Installation done"
            conda list
            echo "libaries printed"
            ls
            cd fine
            echo "start pytest"
            conda run -n test_env python -m pytest test/
            echo "Pytest done"