name: Run dependency checks for glaes

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual run' 
  push:
    branches: 
      - main

  
jobs:
    TestGlaesDevLocal:
        name: Test gdal=(${{ matrix.gdal-version }}, on ${{ matrix.os }} for glaes=${{ matrix.glaes-version }})
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                # os: ["ubuntu-latest","ubuntu-20.04", "macos-latest","macos-13","macos-12", "macos-11","windows-latest","windows-2019"]
                os: ["ubuntu-latest"]
                glaes-version: ["1.2.1"]
                # gdal-version: ["2.4.0","2.4.1","2.4.2","2.4.3","2.4.4","3.0.1","3.0.2","3.0.3","3.0.4","3.4.0", "3.4.1", "3.4.2", "3.4.3", "3.4.4"]
                gdal-version: ["2.4.1"]
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            repository: FZJ-IEK3-VSA/glaes
            path: './glaes'  
            ref: main
        - uses: conda-incubator/setup-miniconda@v3
          with:
            miniforge-version: latest
            channels: conda-forge
            activate-environment: test_env
        - name: Run tests
          shell: pwsh
          run: |
            ls
            echo "LS Done"
            cd glaes
            mamba env create --name glaes_env --yes --file environment.yml
            conda run --name glaes_env pip install . --no-deps
            echo "Installation done"
            conda list --name glaes_env
            echo "libaries printed"
            echo "change directory to test"
            ls
            cd glaes
            echo "start pytest"
            ls
            conda run --name glaes_env pytest
            echo "Pytest done"
            echo "run examples"
        # - name: Run examples
        #   shell: pwsh
        #   run: |
        #     ls
        #     cd ETHOS_PENALPS
        #     cd examples
        #     cd tutorial
        #     conda run --name glaes_env python _1_cooking_example.py
        #     conda run --name glaes_env python _2_cooking_example_more_states.py
        #     conda run --name glaes_env python _3_add_more_cooker_for_parallel_operation.py
        #     conda run --name glaes_env python _4_cooking_and_mixer_exclusive_example.py
        #     cd _5_connect_four_process_steps
        #     conda run --name glaes_env python simulation_starter.py
        #     cd ..
        #     cd ..
        #     cd toffee_production
        #     conda run --name glaes_env python simulation_starter.py
        #     cd ..
        #     cd basic_examples
        #     conda run --name glaes_env python batch_to_batch_1_node_example.py
        #     cd ..
        #     cd b_pillar_manufacturing
        #     conda run --name glaes_env python simulation_starter.py
        #     echo "Running examples terminated"